
exe		=	a.out

#source		=	3_1_observer_push_model.cpp
source		=	3_2_observer_pull_model.cpp


a.out:	$(source)
	@g++ -std=c++14 -o $(exe) -Wall $(source)
	@#clang++ -std=c++14 -Wall $(source)

clean:
	@rm -f $(exe)
