
exe		=	a.out

#source		=	1_proxy.cpp
#source		=	2_composit.cpp
#source		=	3_1_observer_push_model.cpp
#source		=	3_2_observer_pull_model.cpp
#source		=	4_strategy.cpp
#source		=	5_1_doc_app.cpp
source		=	6_visitor.cpp


a.out:	$(source)
	@g++ -std=c++14 -o $(exe) -Wall $(source)
	@#clang++ -std=c++14 -Wall $(source)

clean:
	@rm -f $(exe)
